/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.disuraaberathna.globemed.view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        createCards();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void setUserInfo(String userName, String userRole) {
        welcomeLabel.setText("Welcome, " + userName);
        roleLabel.setText("Role: " + userRole);
    }

    private void createCards() {
        patientRecordsBtn = createFeatureCard("Patient Records", "👥", "Manage patient information, medical history, and personal details");
        appointmentScheduleBtn = createFeatureCard("Appointments", "📅", "Schedule, reschedule, and manage patient appointments");
        billingBtn = createFeatureCard("Billing & Insurance", "💰", "Generate bills and process insurance claims");
        reportsBtn = createFeatureCard("Medical Reports", "📊", "Generate treatment summaries and financial reports");
        manageStaffBtn = createFeatureCard("Staff Management", "👨‍⚕️", "Manage staff roles, permissions, and access control");

        jPanel3.add(patientRecordsBtn);
        jPanel3.add(appointmentScheduleBtn);
        jPanel3.add(billingBtn);
        jPanel3.add(reportsBtn);
        jPanel3.add(manageStaffBtn);
    }

    private JButton createFeatureCard(String title, String icon, String description) {
        JButton btn = new JButton();
        btn.setLayout(new BorderLayout());
        btn.setPreferredSize(new Dimension(300, 200));
        btn.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btn.setBackground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JPanel topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
        topPanel.setOpaque(false);

        JLabel iconLabel = new JLabel(icon);
        iconLabel.setFont(new Font("Comic Sans MS", Font.BOLD, 32));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setFont(new Font("Comic Sans MS", Font.BOLD, 18));
        titleLabel.setForeground(new Color(52, 73, 94));

        topPanel.add(iconLabel);
        topPanel.add(titleLabel);

        JPanel descPanel = new JPanel();
        descPanel.setLayout(new BorderLayout());
        descPanel.setOpaque(false);

        JLabel descLabel = new JLabel();
        descLabel.setText(description);
        descLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        descLabel.setFont(new Font("Courier New", Font.PLAIN, 12));
        descLabel.setForeground(new Color(127, 140, 141));

        descPanel.add(descLabel, BorderLayout.CENTER);

        btn.add(topPanel, BorderLayout.NORTH);
        btn.add(descPanel, BorderLayout.CENTER);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(238, 238, 238));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(Color.WHITE);
            }
        });

        return btn;
    }

    public JButton getPatientRecordsBtn() {
        return patientRecordsBtn;
    }

    public JButton getAppointmentScheduleBtn() {
        return appointmentScheduleBtn;
    }

    public JButton getBillingBtn() {
        return billingBtn;
    }

    public JButton getReportsBtn() {
        return reportsBtn;
    }

    public JButton getManageStaffBtn() {
        return manageStaffBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GlobeMed | Healthcare Management System");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        welcomeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        welcomeLabel.setText("Welcome, Doctor Strange ");

        roleLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(0, 0, 0));
        roleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        roleLabel.setText("Role : DOCTOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 20, 20));
        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JButton patientRecordsBtn;
    private javax.swing.JButton appointmentScheduleBtn;
    private javax.swing.JButton billingBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton manageStaffBtn;
    // End of variables declaration//GEN-END:variables
}
